# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.25-bookworm AS builder

WORKDIR /src
COPY tools/mas-iam-installer/go.mod tools/mas-iam-installer/go.sum /src/tools/mas-iam-installer/
WORKDIR /src/tools/mas-iam-installer
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY tools/mas-iam-installer /src/tools/mas-iam-installer

ARG TARGETARCH=amd64
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    mkdir -p /out/bin \
    && for target in "darwin amd64" "darwin arm64" "linux amd64" "linux arm64"; do \
      set -- ${target}; \
      mkdir -p "/out/bin/$1-$2"; \
      CGO_ENABLED=0 GOOS="$1" GOARCH="$2" \
        go build -trimpath -ldflags="-s -w" -o "/out/bin/$1-$2/est" ./cmd/mas-iam-installer; \
    done

ARG TARGETARCH=amd64
FROM quay.io/lee_forster/mas-external-services-tool:v0.1.0-beta.7-${TARGETARCH}

ARG TARGETARCH=amd64

ENV MAS_EST_REPO_ROOT=/opt/mas-est
WORKDIR /opt/mas-est

COPY scripts /opt/mas-est/scripts
COPY manifests /opt/mas-est/manifests
COPY env /opt/mas-est/env
COPY --from=builder /out/bin /opt/mas-est/runtime/bin
COPY --from=builder /out/bin/linux-${TARGETARCH}/est /usr/local/bin/est

RUN ln -sf /usr/local/bin/est /usr/local/bin/mas-est \
    && chmod +x /usr/local/bin/est /opt/mas-est/scripts/*.sh

ENTRYPOINT ["est"]
CMD ["bootstrap"]
