{{- if .Values.openldap.enabled -}}
{{- $openldap := .Values.openldap -}}
{{- $admin := $openldap.admin -}}
{{- $secretName := (include "keycloak-stack.openldapAdminSecretName" .) | trim -}}
{{- if not $secretName -}}
  {{- fail "Set openldap.admin.secretName or enable openldap.admin.createSecret" -}}
{{- end -}}
{{- $tls := $openldap.tls | default dict -}}
{{- $tlsEnabled := and $openldap.tls $openldap.tls.enabled -}}
{{- $tlsSecretName := "" -}}
{{- if $tlsEnabled -}}
  {{- $tlsSecretName = default (printf "%s-openldap-tls" (include "keycloak-stack.fullname" .)) $openldap.tls.secretName -}}
{{- end -}}
{{- $baseDN := $openldap.config.baseDN -}}
{{- if not $baseDN -}}
  {{- $baseDN = include "keycloak-stack.ldapBaseDN" $openldap.config.domain -}}
{{- end -}}
{{- if not $baseDN -}}
  {{- fail "openldap.config.baseDN or config.domain must be provided" -}}
{{- end -}}
{{- $loadCustomLdif := gt (len $openldap.seedLDIFs) 0 -}}
{{- $saName := default (printf "%s-openldap" (include "keycloak-stack.fullname" .)) $openldap.serviceAccount.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-stack.fullname" . }}-openldap
  labels:
    {{- include "keycloak-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: openldap
spec:
  replicas: {{ $openldap.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-stack.labels" . | nindent 6 }}
      app.kubernetes.io/component: openldap
  template:
    metadata:
      labels:
        {{- include "keycloak-stack.labels" . | nindent 8 }}
        app.kubernetes.io/component: openldap
        {{- with $openldap.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $openldap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $tlsEnabled }}
      initContainers:
        - name: openldap-tls-bootstrap
          image: "{{ $openldap.image.repository }}:{{ $openldap.image.tag }}"
          imagePullPolicy: {{ $openldap.image.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - |
              set -euo pipefail
              mkdir -p /tls-runtime
              cp /tls-src/{{ default "tls.crt" $openldap.tls.certKey }} /tls-runtime/{{ default "tls.crt" $openldap.tls.certKey }}
              cp /tls-src/{{ default "tls.key" $openldap.tls.privateKeyKey }} /tls-runtime/{{ default "tls.key" $openldap.tls.privateKeyKey }}
              cp /tls-src/{{ default "ca.crt" $openldap.tls.caKey }} /tls-runtime/{{ default "ca.crt" $openldap.tls.caKey }}
              chmod 400 /tls-runtime/{{ default "tls.key" $openldap.tls.privateKeyKey }}
              chmod 444 /tls-runtime/{{ default "tls.crt" $openldap.tls.certKey }} /tls-runtime/{{ default "ca.crt" $openldap.tls.caKey }}
          volumeMounts:
            - name: openldap-tls-runtime
              mountPath: /tls-runtime
            - name: openldap-tls-source
              mountPath: /tls-src
      {{- end }}
      serviceAccountName: {{ $saName }}
      {{- if $openldap.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml (omit $openldap.podSecurityContext "enabled") | nindent 8 }}
      {{- end }}
      containers:
        - name: openldap
          image: "{{ $openldap.image.repository }}:{{ $openldap.image.tag }}"
          imagePullPolicy: {{ $openldap.image.pullPolicy }}
          {{- if $openldap.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml (omit $openldap.containerSecurityContext "enabled") | nindent 12 }}
          {{- end }}
          env:
            - name: LDAP_ORGANISATION
              value: {{ $openldap.config.organisation | quote }}
            - name: LDAP_DOMAIN
              value: {{ $openldap.config.domain | quote }}
            - name: LDAP_BASE_DN
              value: {{ $baseDN | quote }}
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: {{ default "password" $admin.passwordKey | quote }}
            {{- if $openldap.config.enableConfigAdmin }}
            - name: LDAP_CONFIG_ADMIN_ENABLED
              value: "true"
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: {{ default "configPassword" $admin.configPasswordKey | quote }}
            {{- end }}
            {{- if $loadCustomLdif }}
            - name: LDAP_SEED_INTERNAL_LDIF_PATH
              value: /seed-internal
            {{- end }}
            {{- if $tlsEnabled }}
            - name: LDAP_TLS
              value: "true"
            - name: LDAP_TLS_CRT_FILENAME
              value: {{ default "tls.crt" $openldap.tls.certKey | quote }}
            - name: LDAP_TLS_KEY_FILENAME
              value: {{ default "tls.key" $openldap.tls.privateKeyKey | quote }}
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: {{ default "ca.crt" $openldap.tls.caKey | quote }}
            - name: LDAP_TLS_ENFORCE
              value: {{ ternary "true" "false" (default false $openldap.tls.enforce) | quote }}
            {{- end }}
            {{- range $extra := $openldap.extraEnv }}
            - name: {{ $extra.name }}
              value: {{ $extra.value | quote }}
            {{- end }}
          ports:
            - name: ldap
              containerPort: {{ $openldap.service.port }}
              protocol: TCP
            {{- if $openldap.service.tlsPort }}
            - name: ldaps
              containerPort: {{ $openldap.service.tlsPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            {{- if $loadCustomLdif }}
            - name: seed-config
              mountPath: /seed-internal
              readOnly: true
            {{- end }}
            {{- if $tlsEnabled }}
            - name: openldap-tls-runtime
              mountPath: /container/service/slapd/assets/certs
            {{- end }}
          resources:
            {{- toYaml $openldap.resources | nindent 12 }}
      volumes:
        - name: ldap-data
          {{- if $openldap.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "keycloak-stack.fullname" . }}-openldap
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: ldap-config
          emptyDir: {}
        {{- if $loadCustomLdif }}
        - name: seed-config
          configMap:
            name: {{ include "keycloak-stack.fullname" . }}-openldap-seed
        {{- end }}
        {{- if $tlsEnabled }}
        - name: openldap-tls-runtime
          emptyDir: {}
        - name: openldap-tls-source
          secret:
            secretName: {{ $tlsSecretName | quote }}
            defaultMode: 0400
        {{- end }}
      {{- with $openldap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $openldap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $openldap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
