{{- if and .Values.openldap.enabled .Values.openldap.seedLDIFs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-stack.fullname" . }}-openldap-seed
  labels:
    {{- include "keycloak-stack.labels" . | nindent 4 }}
data:
{{- range $file := .Values.openldap.seedLDIFs }}
  {{- $target := default (base $file.file) $file.target -}}
  {{- printf "%s: |" $target | nindent 2 }}
{{ $.Files.Get $file.file | indent 4 }}
{{- end }}
{{- end }}
