{{- $openldap := .Values.openldap -}}
{{- if and $openldap.enabled $openldap.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak-stack.fullname" . }}-openldap
  labels:
    {{- include "keycloak-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $openldap.persistence.size }}
  {{- if $openldap.persistence.storageClass }}
  storageClassName: {{ $openldap.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
