apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-stack.fullname" . }}
  labels:
    {{- include "keycloak-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "keycloak-stack.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
