{{- $sa := .Values.keycloak.serviceAccount | default dict -}}
{{- if and (default true $sa.create) (.Values.keycloak.enabled | default true) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mas-iam-stack.keycloakServiceAccountName" . }}
  labels:
    {{- include "mas-iam-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
