{{- $sa := .Values.keycloak.serviceAccount | default dict -}}
{{- $saName := include "mas-iam-stack.keycloakServiceAccountName" . | trim -}}
{{- $createRequested := and (default true $sa.create) (.Values.keycloak.enabled | default true) -}}
{{- $existing := and $createRequested (lookup "v1" "ServiceAccount" .Release.Namespace $saName) -}}
{{- $shouldCreate := and $createRequested (not $existing) -}}
{{- if $shouldCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    {{- include "mas-iam-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
