{{- if and .Values.openldap.enabled .Values.openldap.userPasswords }}
{{- $passwords := .Values.openldap.userPasswords -}}
{{- $secretName := $passwords.secretName | default (printf "%s-openldap-user-passwords" (include "mas-iam-stack.fullname" .)) -}}
{{- $passwordData := $passwords.data | default dict -}}
{{- if and (not $passwords.createSecret) (not $passwords.secretName) }}
  {{- fail "openldap.userPasswords.secretName must be set when openldap.userPasswords.createSecret=false" -}}
{{- end -}}
{{- if and $passwords.createSecret (gt (len $passwordData) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "mas-iam-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: openldap
type: Opaque
data:
{{- range $key, $value := $passwordData }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
